### ISSUE TITLE
Very High Memory use with Beats 6.1.x

### ISSUE THREAD

**Issue by original-brownbear** [logstash-plugins/logstash-input-beats#286] opened 2018-01-24 15:23 UTC
Running Beats 6.1.x with default settings, namely `pipelining: 5` causes the beats input to consume a very large amount of memory.

This situation needs to be improved since the combination of `pipelining: x` with `x > 0` is prohibitively expensive when one Logstash instance is written to by multiple Beats clients and backpressure sets in.

Below graph shows a configuration of just Filebeat -> (beats-input -> stdout)

<img width="768" alt="screen shot 2018-01-24 at 08 16 08" src="https://user-images.githubusercontent.com/6490959/35339523-1cf9efb6-0121-11e8-8c01-55f24d411940.png">

The graph starts off showing just a single Filebeat writing to the LS instance.
At the `5:10` mark a second Filebeat is started way increasing the memory used by the input plugin.

The bulk of the memory use is made up by `org.logstash.beats.Message` instances referenced as shown below:

<img width="2277" alt="screen shot 2018-01-24 at 07 25 52" src="https://user-images.githubusercontent.com/6490959/35339629-5ef611ec-0121-11e8-9512-71b27789ca7b.png">

Possible issues I identified here are:

* We're running `Runtime.getRuntime().availableProcessors() * 4` worker threads in `Server`, that's way too much since we appear to be handling decoding (and its necessary buffering) in each of these.
* `org.logstash.beats.Message` get deserialized before use and hold redundant data as a result of `org.logstash.beats.Message#extractIdentityStream`
   * I would likely help **a lot** making the decoding here lazy and having each `org.logstash.beats.Message` simply reference a `ByteBuf` from an off-heap pool (bonus point for reusing that `ByteBuf` or even the whole `Message` instance)
* We could also optimize decoding of the actual message, constantly allocating `byte[]` for every read in `org.logstash.beats.BeatsParser#decode` puts quite some additional pressure on the GC

```java
                byte[] bytes = new byte[requiredBytes];
                in.readBytes(bytes);
                Message message = new Message(sequence, (Map) MAPPER.readValue(bytes, Object.class));
```

... I'll try to add a few more specific things I found to this issue later. The most important thing as far as I can tell from the profiling is to make `Message` cheaper by ideally just having it be a pointer to a chunk of memory (`ByteBuf` seems easiest, but slices of a `MappedByteBuffer` might be even better since it would allow paging out if necessary, I'd start with `ByteBuf` :)) that gets deserialized when used.

**Comment by praseodym** [comment] 2018-01-24 21:00
I've recently seen Logstash running OOM with its default heap setting (1G), most likely because of this issue.

**Comment by ph** [comment] 2018-01-25 20:30
@original-brownbear @robbavey Nice finding!

**Comment by original-brownbear** [comment] 2018-02-27 18:01
@jakelandis I think these changes are in yes. I'd vouche for a definite improvement of the situation here from https://github.com/logstash-plugins/logstash-input-beats/pull/299.

Not sure if you wanna close it yet @robbavey there's still a lot of improvements to be made, but we could kill it now and revisit if you think that the situation is fixed in terms of crashing the plugin (I'd say so, at least when I tested this, could be different for 500 Beat to 1 LS scenarios though obviously)?

**Comment by robbavey** [comment] 2018-02-27 18:05
@jakelandis Yes the changes are in.

@original-brownbear I'll defer to you as the originator of this bug, but I'd be inclined to close this one and open up a new one for further incremental improvements

**Comment by original-brownbear** [comment] 2018-03-09 12:51
@robbavey I don't think we can close here. Pinged you on another channel about this and it seems we can even reproduce OOMing (now running out of native memory with your changes instead of running out of heap) here without pipelining.
=> We need to constrain the size of the buffering globally to really fix this imo.

**Comment by kovyrin** [comment] 2018-03-09 13:00
The issue has been reliably killing our logstash servers with OOM for the past 24 hours (after upgrading from 6.2.1 to 6.2.2 and the latest beats input plugin). Really need some traction here.

**Comment by jakelandis** [comment] 2018-03-13 23:04
@kovyrin -   One of the root cause [issues](https://github.com/logstash-plugins/logstash-input-beats/issues/310) has been fixed and released. This may help some, but is not a complete solution. 

```
bin/logstash-plugin update logstash-input-beats
```
6.x - `5.0.11`
5.x - `3.1.30`

We have identified where the excessive memory is coming from and working on a strategy to place an upper limit on how much data we can accept.  In the mean time, if you are on the latest version of the plugins you maybe able to increase the max off heap memory used by setting the `-XX:MaxDirectMemorySize=<size>` to a size larger then `-Xmx` value in the jvm.options. This of course assumes the host has enough memory as to not start swapping. (LS doesn't mlock like ES)

**Comment by kovyrin** [comment] 2018-03-14 02:43
@dilchenko JFYI ^

**Comment by dilchenko** [comment] 2018-03-16 16:38
@jakelandis I have upgraded to 5.0.11 plugin version and changed our `-XX:MaxDirectMemorySize` to be slightly larger than `-Xmx`. Seems like the heap usage is a bit more stable now with less frequent GCs, but the problem itself has been resolved for us before any of the changes by reducing `bulk_max_size` in filebeat configs to 128.

**Comment by nitharsandvag** [comment] 2019-10-22 10:02
Any update on this? we are using logstash 6.3.2 and logstash-input-beats-6.0.0 on CentOS 7.6.
After starting logstash, the memory increases permanently until 100% then it crashes...
Our VM has total 64G Ram and xms/x is currently on 31g. (same behavior when setting any number of xms/x)

Logs:
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: [2019-10-22T11:24:02,427][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5043, remote: undefined] Handling exception: Direct buffer memory
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: [2019-10-22T11:24:02,431][WARN ][io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: java.lang.OutOfMemoryError: Direct buffer memory
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: at java.nio.Bits.reserveMemory(Bits.java:175) ~[?:?]
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:118) ~[?:?]
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:317) ~[?:?]
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: at io.netty.buffer.PoolArena.allocate(PoolArena.java:226) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: at io.netty.buffer.PoolArena.reallocate(PoolArena.java:397) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: at io.netty.buffer.PooledByteBuf.capacity(PooledByteBuf.java:118) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:298) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:277) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1069) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: at io.netty.buffer.ByteBufOutputStream.write(ByteBufOutputStream.java:68) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: at java.util.zip.InflaterOutputStream.write(InflaterOutputStream.java:255) ~[?:?]
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: at io.netty.buffer.UnsafeByteBufUtil.getBytes(UnsafeByteBufUtil.java:608) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: at io.netty.buffer.UnsafeByteBufUtil.getBytes(UnsafeByteBufUtil.java:593) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: at io.netty.buffer.PooledUnsafeDirectByteBuf.getBytes(PooledUnsafeDirectByteBuf.java:152) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:960) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: at org.logstash.beats.BeatsParser.decode(BeatsParser.java:181) ~[logstash-input-beats-6.0.0.jar:?]
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:353) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-all-4.1.30.Final.jar:4.1.30.Final]
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.30.Final.jar:4.1.30.Final]
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: at java.lang.Thread.run(Thread.java:834) [?:?]
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: Suppressed: java.lang.OutOfMemoryError: Direct buffer memory
Oct 22 11:24:02 logstash01.xxxxxxxx.net podman[25042]: at java.nio.Bits.reserveMemory(Bits.java:175) ~[?:?]

Thanks

**Comment by gwsales** [comment] 2019-10-31 22:13
I have this issue too with winlogbeats.

**Comment by nitharsandvag** [comment] 2019-11-01 09:27
We got that issue fixed! It was a problem with VMware, the allocated RAM was not available on VMware host. Now we allocated fixed RAM size to the VM and is working fine. Hope it may help others to solve the issue.

**Comment by kares** [comment] 2020-06-30 13:03
Going to close this as it leads to confusion when the beats plugin still runs out of (direct) off-heap memory.
There's certainly room for further improvements but I went through the code and the original problems seems to be adressed:

> Possible issues I identified here are:

>    We're running `Runtime.getRuntime().availableProcessors() * 4` worker threads in Server, that's way too much since we appear to be handling decoding (and its necessary buffering) in each of these.

defaults is `Runtime.getRuntime().availableProcessors()` workers

>    `org.logstash.beats.Message` get deserialized before use and hold redundant data as a result of `org.logstash.beats.Message#extractIdentityStream`

for v2 of the protocol this is implemented

>        I would likely help a lot making the decoding here lazy and having each `org.logstash.beats.Message` simply reference a `ByteBuf` from an off-heap pool (bonus point for reusing that `ByteBuf` or even the whole `Message` instance)

this is the case v2 protocol is handling the `Message`

>    We could also optimize decoding of the actual message, constantly allocating `byte[]` for every read in `org.logstash.beats.BeatsParser#decode` puts quite some additional pressure on the GC

there's no direct `byte[]` allocation anymore

**Closed by kares** 2020-06-30 13:03 UTC
Labels: crashes, resiliency
