### ISSUE TITLE
Can't update the plugin

### ISSUE THREAD

**Issue by gelato** [logstash-plugins/logstash-input-beats#87] opened 2016-05-20 08:03 UTC
While i'm trying to update the plugin i recieve confirmation dialog:
You are updating logstash-input-beats to a new version 3.0.2, which may not be compatible with 2.2.8. are you sure you want to proceed (Y/N)?
But still nothing happens: 
Updating logstash-input-beats
No plugin updated
Plugin is still 2.2.8 and when i try to use it i recieve error:
"undefined method `each' for nil:NilClass>"
Logstash version: 2.3.2

**Comment by ph** [comment] 2016-05-27 13:42
The master branch of this plugin is 3.0 but its only compatible with LS 5.0, so the current last compatible version should be 2.2.8. 

This message is a bug, LS shouldn't offer you to install an incompatible version, we have created an issue on the logstash repo to track it. You can follow the details at https://github.com/elastic/logstash/issues/5279, If you down mind I will close this issue.

**Closed** 2016-07-20 20:04 UTC

**Comment by KIVagant** [comment] 2016-08-19 20:55
I have same issue with logstash 2.3.4.

**Comment by jordansissel** [comment] 2016-08-19 21:32
@KIVagant the message "You are updating logstash-input-beats to a new version 3.0.2, which may not be compatible with 2.2.8. are you sure you want to proceed (Y/N)?" is caused by a bug in the plugin manager which offers you a version (3.0.2) of the plugin that is not compatible with your version of Logstash (v2.3.4). This bug is tracked here: https://github.com/elastic/logstash/issues/5279

the beats input plugin version 2.2.8 is the latest version available for Logstash 2.3.x.

**Comment by KIVagant** [comment] 2016-08-19 21:34
Thank you, @jordansissel . Sorry, I missed the link above.
