### ISSUE TITLE
LS 5.1.1 beats input plugin unsupported cipher suite TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384

### ISSUE THREAD

**Issue by buzzdeee** [logstash-plugins/logstash-input-beats#174] opened 2016-12-22 07:48 UTC
I'm testing LS 5.1.1 (ES/Kibana are already at that version)

Because of this issue 
https://github.com/elastic/logstash/issues/6121
I had this in my beats input definition:

```
  beats {
    port => 12344
    ssl => true
    ssl_certificate => "/etc/logstash/logstash.crt"
    ssl_key => "/etc/logstash/logstash.key"
    ssl_certificate_authorities => [ "/etc/logstash/logstash-ca.crt" ]
    ssl_verify_mode => "force_peer"
    cipher_suites => [ 'TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256' ]
    type => "logs"
  }
```

that was working properly with LS 2.4.1.
Then on startup of LS 5.1.1 I got:

```
[2016-12-21T23:36:25,848][INFO ][logstash.inputs.beats    ] Beats inputs: Starting input listener {:address=>"0.0.0.0:12344"}
[2016-12-21T23:36:26,400][ERROR][logstash.agent           ] Pipeline aborted due to error {:exception=>#<LogStash::ConfigurationError: Cipher `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256` is not available>, :backtrace=>["/usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-3.1.12-java/lib/logstash/inputs/beats.rb:184:in `create_server'", "/usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-3.1.12-java/lib/logstash/inputs/beats.rb:172:in `register'", "/usr/local/logstash/logstash-core/lib/logstash/pipeline.rb:353:in `start_inputs'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/local/logstash/logstash-core/lib/logstash/pipeline.rb:352:in `start_inputs'", "/usr/local/logstash/logstash-core/lib/logstash/pipeline.rb:228:in `start_workers'", "/usr/local/logstash/logstash-core/lib/logstash/pipeline.rb:183:in `run'", "/usr/local/logstash/logstash-core/lib/logstash/agent.rb:292:in `start_pipeline'"]}
[2016-12-21T23:36:26,518][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2016-12-21T23:36:29,452][WARN ][logstash.agent           ] stopping pipeline {:id=>"main"}
```

so I removed the cipher_suites parameter, in order to let the plugin pick some default cipher, but then I get on startup:

```
 Sending Logstash's logs to /var/log/logstash which is now configured via log4j2.properties
[2016-12-21T23:40:13,289][INFO ][logstash.inputs.beats    ] Beats inputs: Starting input listener {:address=>"0.0.0.0:12344"}
[2016-12-21T23:40:13,831][ERROR][logstash.agent           ] Pipeline aborted due to error {:exception=>#<LogStash::ConfigurationError: Cipher `TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384` is not available>, :backtrace=>["/usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-3.1.12-java/lib/logstash/inputs/beats.rb:184:in `create_server'", "/usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-3.1.12-java/lib/logstash/inputs/beats.rb:172:in `register'", "/usr/local/logstash/logstash-core/lib/logstash/pipeline.rb:353:in `start_inputs'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/local/logstash/logstash-core/lib/logstash/pipeline.rb:352:in `start_inputs'", "/usr/local/logstash/logstash-core/lib/logstash/pipeline.rb:228:in `start_workers'", "/usr/local/logstash/logstash-core/lib/logstash/pipeline.rb:183:in `run'", "/usr/local/logstash/logstash-core/lib/logstash/agent.rb:292:in `start_pipeline'"]}
[2016-12-21T23:40:13,965][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2016-12-21T23:40:16,946][WARN ][logstash.agent           ] stopping pipeline {:id=>"main"}

```

I'm on OpenBSD amd64 6.0-snapshot, jdk-1.8.0.112, LS 5.1.1. 

downgrading to 4.2.1 again, and the issue is gone for the time being.

**Comment by academ1c** [comment] 2017-01-30 13:18
@buzzdeee Hi, this proble may with tmp dir for natty ssl lib. Create tmp  dir without option noexec.
It my jvm.options file


```
-Xms256m
-Xmx1g
-XX:+UseParNewGC
-XX:+UseConcMarkSweepGC
-XX:CMSInitiatingOccupancyFraction=75
-XX:+UseCMSInitiatingOccupancyOnly
-XX:+DisableExplicitGC
-Djava.awt.headless=true
-Dfile.encoding=UTF-8
-XX:+HeapDumpOnOutOfMemoryError
-Dio.netty.native.workdir=/usr/share/logstash/tmp
```

**Comment by ph** [comment] 2017-01-31 15:56
I can confirm that @academ1c is right here, and the issue is when netty tried to uncompressed the native library, changing the workdir or the logstash tmp dir in `config/logstash.yml` will fix the issue.

I've created a #181 to yield a better error than the missing ciphers.

**Comment by buzzdeee** [comment] 2017-02-08 22:04
Hi,

sorry for getting back late, only found time today to look at it again.
I'm still at the same LS 5.1.1, and I  added:

-Dio.netty.native.workdir=/usr/local/yalla
to /etc/logstash/jvm.options
and did a 
mkdir /usr/local/yalla && chmod 777 /usr/local/yalla

just to be on the safe side, then I ran logstash with --log.level debug

besides all the startup debug logs, then before the error message comes I now
recognized I get:

`[2017-02-08T22:48:42,881][DEBUG][io.netty.util.internal.logging.InternalLoggerFactory] Using Log4J as the default logging framework
[2017-02-08T22:48:42,900][DEBUG][io.netty.util.internal.NativeLibraryLoader] -Dio.netty.native.workdir: /usr/local/yalla
[2017-02-08T22:48:42,903][DEBUG][io.netty.util.internal.NativeLibraryLoader] Unable to load the library: netty-tcnative-openbsd-x86_64.
java.lang.UnsatisfiedLinkError: no netty-tcnative-openbsd-x86_64 in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867) ~[?:1.8.0_112]
        at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[?:1.8.0_112]
        at java.lang.System.loadLibrary(System.java:1122) ~[?:1.8.0_112]
        at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:189) ~[netty-all-4.1.3.Final.jar:4.1.3.Final]
        at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:161) [netty-all-4.1.3.Final.jar:4.1.3.Final]
        at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:325) [netty-all-4.1.3.Final.jar:4.1.3.Final]
        at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:90) [netty-all-4.1.3.Final.jar:4.1.3.Final]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_112]
        at java.lang.Class.forName(Class.java:348) [?:1.8.0_112]
        at org.jruby.javasupport.JavaSupport.loadJavaClass(JavaSupport.java:149) [?:?]
        at org.jruby.javasupport.JavaSupport.loadJavaClassVerbose(JavaSupport.java:158) [?:?]
        at org.jruby.javasupport.JavaClass.forNameVerbose(JavaClass.java:192) [?:?]
        at org.jruby.javasupport.JavaClass.for_name(JavaClass.java:204) [?:?]
        at org.jruby.javasupport.Java.get_proxy_class(Java.java:419) [?:?]
        at org.jruby.javasupport.JavaUtilities.get_proxy_class(JavaUtilities.java:34) [?:?]
        at org.jruby.javasupport.JavaUtilities$INVOKER$s$1$0$get_proxy_class.call(JavaUtilities$INVOKER$s$1$0$get_proxy_class.gen) [?:?]
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168) [?:?]
        at rubyjit.Object$$java_import_44d51cc907f9e71af2ee62ef8a406525526d22691252169911.block_0$RUBY$__file__(file:/usr/local/logstash/vendor/jruby/lib/jruby.jar!/jruby/java/core_ext/object.rb:27) [?:?]
        at rubyjit$Object$$java_import_44d51cc907f9e71af2ee62ef8a406525526d22691252169911$block_0$RUBY$__file__.call(rubyjit$Object$$java_import_44d51cc907f9e71af2ee62ef8a406525526d22691252169911$block_0$RUBY$__file__) [?:?]
        at org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:135) [?:?]
        at org.jruby.runtime.Block.yield(Block.java:142) [?:?]
        at org.jruby.RubyArray.collect(RubyArray.java:2400) [?:?]
        at org.jruby.RubyArray.map19(RubyArray.java:2414) [?:?]
        at org.jruby.RubyArray$INVOKER$i$0$0$map19.call(RubyArray$INVOKER$i$0$0$map19.gen) [?:?]
        at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143) [?:?]
        at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154) [?:?]`

does that netty just not have a library for OpenBSD?

unzipping /usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-3.1.12-java/vendor/jar-dependencies/io/netty/netty-tcnative-boringssl-static/1.1.33.Fork23/netty-tcnative-boringssl-static-1.1.33.Fork23.jar

I only find a 
find . -name "*so"
./META-INF/native/libnetty-tcnative-linux-x86_64.so

as already said, with the 2.4 version of LS, I can happily run beats via SSL, as I understand, there were heavy rewrites.

**Comment by jordansissel** [comment] 2017-02-08 22:06
We don't have tests that run on OpenBSD, so we wouldn't catch this.

I agree with your summary, though, that netty doesn't ship openbsd libraries.

**Comment by jordansissel** [comment] 2017-02-08 22:26
I submitted too soon, sorry about that --

@ph and I have been talking about netty, tcnative, and java ssl, and we will see about having Netty use the Java SSL library instead of the tcnative library (boringssl). I'll file a separate issue about that.

**Comment by buzzdeee** [comment] 2017-02-08 22:34
Bummer, that's quite a disappointing regression for me then. My ELK stack is based on OpenBSD ports/packages, and runs fine on OpenBSD for quite some time now. 
For OpenBSD -current, Kibana/ES have already ports/packages for 5.X versions, only LS is lagging behind because of my negative test results with regard to beats and SSL.

Maybe an alternative netty could be bundled into the jar, i.e. reading 
http://netty.io/wiki/forked-tomcat-native.html
there is a netty-tcnative-{os_arch} that might do the trick, linking against external libapr and openssl? or there is a netty-tcnative-libressl-static-{os_arch}
but that is unfortunately "coming soon". Because libressl is an OpenBSD project, it might be netty will support/provide OpenBSD statically linked .so files? I've no idea, not checked, and I'm blindly guessing here ;)

As you mention, if the Java SSL library is also a viable solution, more portable, then I'm all for it. My java knowledge is rather marginal ;)

**Comment by ph** [comment] 2017-02-08 22:35
@buzzdeee I think moving to java crypto will be the best solution.

**Comment by jordansissel** [comment] 2017-02-08 22:36
Yeah, we are very likely to move away from tcnative/boringssl and switch to java crypto. The issue tracking this is here: https://github.com/logstash-plugins/logstash-input-beats/issues/188

Positive Impact: using Java crypto will make the beats input work on all platforms, not just ones on which Netty project releases native libraries.

**Comment by ph** [comment] 2017-02-08 22:37
@buzzdeee I don't have time release for that, but I have other issue in the input to look into, I will try to merge it at the same time.

**Comment by buzzdeee** [comment] 2017-02-08 22:39
whatever makes it work on OpenBSD again makes me happy. I've no real clue about java, and I was really happy that I kind of luckily seem to have found the root cause of my trouble.

**Comment by buzzdeee** [comment] 2017-04-13 20:39
ES/Kibana 5.3 seems to be all fine on OpenBSD, just gave LS a shot, but still stuck here with 2.4 :(

**Comment by dlangille** [comment] 2017-04-24 15:09
Anything we can do to help?

**Comment by jordansissel** [comment] 2017-04-24 16:42
I'm going to close this in favor of #188 which will work towards a solution to this problem.

See y'all over on #188 :)

**Closed by jordansissel** 2017-04-24 16:42 UTC
Labels: bug
