### ISSUE TITLE
Beats does not honor 'host' setting listening on specific host IP

### ISSUE THREAD

**Issue by wasmum** [logstash-plugins/logstash-input-beats#171] opened 2016-12-01 21:24 UTC
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For all general issues, please provide the following details for fast resolution:

- Version: logstash-2.4.0
- Operating System: CentOS Linux release 7.2.1511
- Config File  http://pastebin.com/LLMNZrhJ
```
cat logstash.conf ; netstat -tupln |grep -i list
input {
  beats {
    host => "10.48.79.67"
    port => "5044"
    ssl => "true"
    congestion_threshold => "40"
    ssl_certificate => "/etc/logstash/logstash.crt"
    ssl_key => "/etc/logstash/logstash.key"
  }
}
 
 
output {
  elasticsearch {
    hosts => ["esnode-upstrem:9200"]
    sniffing => true
    manage_template => false
    index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
    document_type => "%{[@metadata][type]}"
  }
}
tcp        0      0 0.0.0.0:8010            0.0.0.0:*               LISTEN      10322/python
tcp        0      0 0.0.0.0:8013            0.0.0.0:*               LISTEN      10322/python
tcp        0      0 0.0.0.0:5044            0.0.0.0:*               LISTEN      16970/java
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      2546/sshd
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      2910/master
tcp        0      0 0.0.0.0:8008            0.0.0.0:*               LISTEN      10380/python
tcp6       0      0 :::22                   :::*                    LISTEN      2546/sshd
```

- Steps to Reproduce:
Install logstash 
configure beats input with a specific host ip declaration
restart logstash
verify logstash is listening on the ip you specified or the default all ip configuration (0.0.0.0)

**Comment by ph** [comment] 2016-12-02 00:54
Hello @wasmum thanks for reporting it, this is a duplicate of #146 and it was fixed in version [3.1.6](https://github.com/logstash-plugins/logstash-input-beats/blob/master/CHANGELOG.md#316)  of the plugin. I suggest that you update your plugin using the following command:


```
bin/logstash-plugin update logstash-input-beats
```

**Closed by ph** 2016-12-02 00:54 UTC
