### ISSUE TITLE
Build is Broken, Jar Dependencies are not Bundled Starting with 3.1.16

### ISSUE THREAD

**Issue by original-brownbear** [logstash-plugins/logstash-input-beats#210] opened 2017-06-03 07:23 UTC
See this:

<img width="325" alt="screen shot 2017-06-03 at 09 21 55" src="https://cloud.githubusercontent.com/assets/6490959/26751627/1f911228-483e-11e7-9381-c4a1efacd2fc.png">

Apparently, the build stopped bundling jar dependencies breaking Core ITs with missing dependencies like here: https://travis-ci.org/elastic/logstash/jobs/238998526#L1426

```sh
[2017-06-03T04:21:41,504][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::PluginLoadingError", :message=>"Couldn't find any input plugin named 'beats'. Are you sure this is correct? Trying to load the beats input plugin resulted in this error: Problems loading the requested plugin named beats of type input. Error: RuntimeError \n\n\tyou might need to reinstall the gem which depends on the missing jar or in case there is Jars.lock then resolve the jars with `lock_jars` command\n\nno such file to load -- io/netty/netty-all/4.1.3.Final/netty-all-4.1.3.Final (LoadError)"}
```

**Comment by original-brownbear** [comment] 2017-06-03 07:24
@suyograo while you fixed it I made the issue :D

**Comment by jakelandis** [comment] 2017-06-03 14:33
Hmm...

I ran the same commands as [jarvis publish](https://github.com/elastic/jarvis/blob/master/lib/jarvis/commands/publish.rb#L30) locally and got the correct results. _(I don't have the ruby gems credentials, so nothing was published)_

I don't think the root cause is code in this plugin, though a change can be made here to fail properly.  

```
du -h  logstash-input-beats-4.0.0-java.gem 
8.0M	logstash-input-beats-4.0.0-java.gem
``` 

Normal vendor:

```
bundle exec rake vendor
BUILD SUCCESSFUL
echo $?
0
```

Break the vendor by introducing a typo in to build script
```
bundle exec rake vendor
BUILD FAILED
echo $?
0
```

I think perhaps an issue occured during the ```rake vendor```, but [jarvis](https://github.com/elastic/jarvis/blob/master/lib/jarvis/exec.rb#L30) didn't notice due to the exit code. 

A small change to rake build task should allow jarvis to properly kill the build on error. PR coming...

```
 task :vendor do
-  system("./gradlew vendor")
+  exit(1) unless system './gradlew vendor'
   version = File.read("VERSION").strip
 end
 ```

(with change) Break the vendor by introducing a typo in to build script
```
bundle exec rake vendor
BUILD FAILED
echo $?
1
```

**Comment by original-brownbear** [comment] 2017-06-03 16:36
Hmm last I remember Jarvis publishing of gems that contained Java was broken, @suyograo do you know more? :)

**Comment by jakelandis** [comment] 2017-06-03 20:08
For clarity, the proposed change here does not fix the issue. It should however, prevent a broken gem _(due to gradlew failures)_  from getting published.

**Comment by ph** [comment] 2017-06-05 14:54
@original-brownbear Jarvis was always able to publish gem if the jars are packed when running the `bundle exec rake vendor` tasks. We recently change the host of jarvis which might have affected the environment. I will take a look.

@suyograo Can you push your VERSION change to this repo, master is still fixed at 4.0.0 and 4.0.1 was released manually.

**Comment by jakelandis** [comment] 2017-06-05 15:18
Reopening to ensure that @suyograo  changes are committed to master.

**Comment by ph** [comment] 2017-06-05 15:52
After investigating, I have found the issue, we have recently migrated Jarvis to a larger ec2 instance, and we didn't use the JDK, so the beats input build was failing. All Java-based plugins were probably failing on Travis.

**Closed** 2017-06-06 20:44 UTC
